# Generated by Django 4.2.16 on 2024-11-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=64)),
                ('product_avaliblity', models.BooleanField(default=True)),
                ('product_avalible_quantity', models.IntegerField(default=1)),
                ('product_price', models.IntegerField(default=1)),
                ('product_description', models.TextField()),
            ],
        ),
    ]
