# Generated by Django 4.2.16 on 2024-11-03 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_product_product_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
